name: Hello World

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    hello_world:
        name: Print hello
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo Hello World
